DROP DATABASE IF EXISTS workoutdb;
CREATE DATABASE workoutdb;
USE workoutdb;

CREATE TABLE Users (
  id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(300) NOT NULL,
  email VARCHAR(300) NOT NULL,
  userPassword VARCHAR(300) NOT NULL
);

CREATE TABLE workouts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stroke VARCHAR(20) NOT NULL,
  laps INT(10) NOT NULL,
  baseTime INT(10) NOT NULL
);